### ISSUE TITLE
1.13.2 and below support

### ISSUE THREAD

**Issue by untuned** [foncused/DuoAuth#1]
When setting `api-version` to 1.14, it will not load on 1.13 servers or below.

**Comment by foncused** [comment]
I removed this from the plugin.yml in v1.0.8 but do not intend to test on lower versions than the latest available (1.14.4). Would you mind letting me know if this resolves the issue?

Thanks!

**Comment by ghost** [comment]
Support for 1.12.2?

**Comment by foncused** [comment]
Since there is a real interest in supporting lower versions, I took the time to test on 1.13.2 and 1.12.2 and both revealed no compatibility issues. DuoAuth v1.0.11 works on both.
